[build]
  publish   = "public"
  functions = "functions"

# [[redirects]]
#   from   = "/:target-:personality-:intention"
#   to     = "/.netlify/functions/recommend?target=:target&personality=:personality&intention=:intention"
#   status = 200
#   force  = true
